# build.yaml. This file is quite powerful, see https://pub.dev/packages/build_config

targets:
  $default:
    builders:
      drift_dev:
        options:
          # Relative path to the database file
          databases:
            app_database: lib/db/app_db.dart

          # Other Drift options
          store_date_time_values_as_text: true
          sql:
            dialect: sqlite
            options:
              modules: [fts5]
