import 'dart:async';
import 'dart:io';
import 'package:bloc/bloc.dart';
import 'package:equatable/equatable.dart';
import 'package:path_provider/path_provider.dart';
import 'package:path/path.dart' as path;
import 'package:flutter_app/dao/resource_db.dart';
import 'package:flutter_app/models/resource.dart';

part 'resource_event.dart';

part 'resource_state.dart';

class ResourceBloc extends Bloc<ResourceEvent, ResourceState> {
  final ResourceDB _resourceDB;

  ResourceBloc(this._resourceDB) : super(ResourceInitial()) {
    on<LoadResourcesEvent>(_onLoadResources);
    on<AddResourceEvent>(_onAddResource);
    on<RemoveResourceEvent>(_onRemoveResource);
    on<ClearResourcesEvent>(_onClearResources);
  }

  void _onLoadResources(
      LoadResourcesEvent event, Emitter<ResourceState> emit) async {
    emit(ResourceLoading());
    try {
      final resources = await _resourceDB.getResourcesByTaskId(event.taskId);
      emit(ResourceLoaded(resources));
    } catch (e) {
      emit(ResourceError('Failed to load resources: ${e.toString()}'));
    }
  }

  void _onAddResource(
      AddResourceEvent event, Emitter<ResourceState> emit) async {
    emit(ResourceLoading());
    try {
      // Get the next resource ID from database
      final nextId = await _resourceDB.getNextResourceId();

      // Copy image from gallery to internal storage using the database ID
      final internalPath =
          await _copyImageToInternalStorage(event.imagePath, nextId);

      // Create resource model
      final resource = ResourceModel(
        id: 0, // Will be auto-generated by database
        path: internalPath,
        taskId: event.taskId,
        createTime: DateTime.now(),
      );

      // Insert resource into database
      await _resourceDB.insertResource(resource);

      // Emit success state first
      emit(const ResourceAddSuccess('Resource added successfully'));
    } catch (e) {
      emit(ResourceError('Failed to add resource: ${e.toString()}'));
    }
  }

  void _onRemoveResource(
      RemoveResourceEvent event, Emitter<ResourceState> emit) async {
    emit(ResourceLoading());
    try {
      // Delete file from internal storage
      await _deleteFileFromInternalStorage(event.filePath);

      // Delete resource from database
      await _resourceDB.deleteResource(event.resourceId);

      // Emit success state first
      emit(const ResourceRemoveSuccess('Resource deleted successfully'));
    } catch (e) {
      emit(ResourceError('Failed to remove resource: ${e.toString()}'));
    }
  }

  Future<String> _copyImageToInternalStorage(
      String sourcePath, int resourceId) async {
    final appDocDir = await getApplicationDocumentsDirectory();
    final resourcesDir = Directory(path.join(appDocDir.path, 'resources'));

    // Create resources directory if it doesn't exist
    if (!await resourcesDir.exists()) {
      await resourcesDir.create(recursive: true);
    }

    // Generate filename using database ID
    final extension = path.extension(sourcePath);
    final fileName = 'resource_$resourceId$extension';
    final destinationPath = path.join(resourcesDir.path, fileName);

    // Copy file
    final sourceFile = File(sourcePath);
    await sourceFile.copy(destinationPath);

    return destinationPath;
  }

  Future<void> _deleteFileFromInternalStorage(String filePath) async {
    try {
      final file = File(filePath);
      if (await file.exists()) {
        await file.delete();
      }
    } catch (e) {
      // Log error but don't throw - database cleanup is more important
      print('Warning: Failed to delete file $filePath: $e');
    }
  }

  FutureOr<void> _onClearResources(
      ClearResourcesEvent event, Emitter<ResourceState> emit) async {
    emit(ResourceLoading());
    try {
      final resources = await _resourceDB.getUnassignedResources();
      for (final resource in resources) {
        // Delete file from internal storage
        await _deleteFileFromInternalStorage(resource.path);

        // Delete resource from database
        await _resourceDB.deleteResource(resource.id);
      }
      // Emit success state first
      emit(const ResourceRemoveSuccess('Resource deleted successfully'));
    } catch (e) {
      emit(ResourceError('Failed to remove resource: ${e.toString()}'));
    }
  }
}
